#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stringcase
Version  : 1.2.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/f3/1f/1241aa3d66e8dc1612427b17885f5fcd9c9ee3079fc0d28e9a3aeeb36fa3/stringcase-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f3/1f/1241aa3d66e8dc1612427b17885f5fcd9c9ee3079fc0d28e9a3aeeb36fa3/stringcase-1.2.0.tar.gz
Summary  : String case converter.
Group    : Development/Tools
License  : MIT
Requires: stringcase-python = %{version}-%{release}
Requires: stringcase-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
stringcase
==========
Convert string cases between camel case, pascal case, snake case etc...

%package python
Summary: python components for the stringcase package.
Group: Default
Requires: stringcase-python3 = %{version}-%{release}

%description python
python components for the stringcase package.


%package python3
Summary: python3 components for the stringcase package.
Group: Default
Requires: python3-core

%description python3
python3 components for the stringcase package.


%prep
%setup -q -n stringcase-1.2.0
cd %{_builddir}/stringcase-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582832639
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
